version: "3.9"
services:
  trainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: trainer:v1_0
    working_dir: /src
    volumes:
    - .:/src
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
    ports:
      - "8000:8000"
    command: >
     bash -c "vue ui --headless --port 8000 --host 0.0.0.0"
    # command: >
    #  bash -c "python3 ./processor.py"
    # command: >
    #  bash -c "python3 ./trainer/train.py"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]   